### ISSUE TITLE
Xcode 11 beta 4 support 

### ISSUE THREAD

**Issue by ada10086** [AudioKit/Specs#2]
I just upgraded Xcode to beta 4 and I got error "Compiled module was created by an older version of the compiler; rebuild 'AudioKit' and try again:" previously I had Xcode 11 beta 1 and it showed module was created by a newer version. So I guess this only works for either beta 2 or 3 ??

**Comment by colinhumber** [comment]
This should be fixed now and working in the latest beta (b5). Tested and using it on Xcode 11b5 now.
