### ISSUE TITLE
Error- Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by azeemohd786** [AudioKit/Specs#3]
I had issue "Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: ". Then I changed the pod file with 'AudioKit', '=4.7.2.b1' along with repo as per instruction but getting this error ,

```
Desktop/AudioKit/Pods/AudioKit/iOS/AudioKit.framework/AudioKit(AKDCBlockAudioUnit.o) compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file 'Desktop/AudioKit/Pods/AudioKit/iOS/AudioKit.framework/AudioKit' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by megastep** [comment]
If you're on Xcode 11 you should use AudioKit 4.9 in the main CocoaPods repo - the pods in this repo are by nature temporary while we work on new features or for pre-release versions of Xcode.
