### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by ElenaVielva** [AudioKit/Specs#4]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler.

Issue on AudioKit was resolved on version 4.9.2 (https://github.com/AudioKit/AudioKit/issues/1911#issuecomment-549005210).

Using pod 'AudioKit/Core', '=4.8.1.b1'

**Comment by aure** [comment]
I'm confused as to what this issue is.

**Comment by megastep** [comment]
Yeah just don't force using an old beta release version and just stick with the current version of the pod. 4.8.1b1 will definitely not work with recent versions of Xcode,
