### ISSUE TITLE
Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.5.2

### ISSUE THREAD

**Issue by quaternionboy** [AudioKit/Specs#5]
Trying to run AudioKit Synthone in XCode 12 (12.0 & 12.5.1)  and 13 (13.2.1)

`pod install` and `pod update` done but get:

- in XCode 13:

`Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.5.2`

- in XCode 12:

`Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.3`
___

So I updated `Podfile` with last Audiokit compiled framework version `5.0.b2` and platform `11.0` (https://github.com/AudioKit/Specs ) but still get same error

`Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.3`

**Comment by megastep** [comment]
Yes, those pods were binary distributions of xcframeworks compiled with earlier versions of Xcode. So they won't link with newer versions.

We've pretty much deprecated CocoaPods support in the current version of AudioKit; you should use the Swift Package Manager instead. We won't be making updated binary pods available.
